- name: Setup Repositories
  include_tasks: repos.yml

- name: Install yum utils and wget
  yum:
    state: present
    name:
      - yum-utils
      - wget

- name: Gather Facts
  setup:

- name: Output the current kernel version
  debug:
    msg: "Kernel Version is {{ ansible_kernel }}"


- name: Patch Server Tasks
  when:
    - ansible_kernel is not version_compare('5.18', '<')
    - patch_server
  include_tasks: patch.yml