---
- name: Install yum utils and wget
  yum:
    state: present
    name:
      - yum-utils
      - wget

- name: Gather Facts
  setup:

- name: Output the current kernel version
  debug:
    msg: "Kernel Version is {{ ansible_kernel }}"

- name: Patch Server Tasks
  when:
    - patch_server
  include_tasks: patch.yml