---
- name: tss - Install tpm2-tss dependencies
  yum:
    name:
      - tpm2-tss
      - git
      - autoconf
      - automake
      - pkg-config
      - libtool
      - autoconf-archive
      - doxygen

- name: tss - Install Dependencies
  shell: |
    dnf builddep -y tpm2-tss

- name: tss - Create Directory for tpm2-tss
  file:
    state: directory
    path: "/tmp/tpm2-tss"

- name: tss - Download Git Repo
  git:
    repo: https://github.com/tpm2-software/tpm2-tss.git
    version: "{{ tpm_tss_version }}"
    dest: "/tmp/tpm2-tss"

- name: tss - Execute tss bootstrap script
  shell: |
    ./bootstrap
  args:
    chdir: /tmp/tpm2-tss
    creates: /tmp/tpm2-tss/configure

- name: tss - Execute tss configure script
  shell: |
    ./configure --with-udevrulesdir=/etc/udev/rules.d
  args:
    chdir: /tmp/tpm2-tss
    #creates: /tmp/tpm2-tss/Makefile

- name: tss - Compile Code using Make
  shell: |
    make -j$(nproc)
  args:
    chdir: /tmp/tpm2-tss
    #creates: /tmp/tpm2-tss/install-sh
  environment:
    GITIGNOREFILES:  # https://github.com/tpm2-software/tpm2-tss/issues/1636

- name: tss - Install tpm-tss
  shell: |
    make install
  args:
    chdir: /tmp/tpm2-tss
    creates: /usr/local/include/tss2/tss2_common.h

- name: tss - Reload Udev Rules
  shell: |
    udevadm control --reload-rules && udevadm trigger

- name: tss - Update Run-Time bindings
  shell: |
    ldconfig