- name: Install dependencies for this module
  yum:
    state: present
    name:
      - yum-utils
      - wget

- name: Install build tools
  yum:
    name: "@Development tools"
    state: present

- name: Install other Dependencies for the tools
  yum:
    name:
      - openssl-devel
      - libcmocka-devel
      - libgcrypt-devel
      - uthash-devel
      - autoconf-archive
      - libtool
      - pkgconfig
      - dbus-devel
      - glib2-devel
      - m4
      - libcurl-devel
