---
- name: Install tpm2-abrmd dependencies
  yum:
    name:
      - autoconf
      - automake
      - libtool
      - autoconf-archive
      - glib
      - pkg-config
      - gcc
      - glib2-devel

- name: Setup TSS User
  user:
    name: tss
    system: true

- name: Create Directory for tpm2-abrmd
  file:
    state: directory
    path: "/tmp/tpm2-abrmd"

- name: Download Git Repo
  git:
    repo: https://github.com/tpm2-software/tpm2-abrmd.git
    version: "{{ tpm_abrmd_version }}"
    dest: "/tmp/tpm2-abrmd"

- name: Execute tss bootstrap script
  shell: |
    ./bootstrap
  args:
    chdir: /tmp/tpm2-abrmd
    creates: /tmp/tpm2-abrmd/configure

- name: Execute abrmd configure script
  shell: |
    ./configure --with-systemdsystemunitdir=/etc/systemd/system
  args:
    chdir: /tmp/tpm2-abrmd
    creates: /tmp/tpm2-abrmd/Makefile
  environment:
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig

- name: Compile Code using Make
  shell: |
    make
  args:
    chdir: /tmp/tpm2-abrmd
    creates: /tmp/tpm2-abrmd/src/tpm2-abrmd

- name: Install tpm-abrmd
  shell: |
    make install
  args:
    chdir: /tmp/tpm2-abrmd
    creates: /usr/local/sbin/tpm2-abrmd

- name: Update Run-Time bindings
  shell: |
    ldconfig

- name: Reload systemd daemons
  shell: |
    systemctl daemon-reload

- name: Enable tpm2-abrmd service
  service:
    name: tpm2-abrmd
    state: started
    enabled: true
  ignore_errors: true
