---
- name: tools - Install tpm2-tools dependencies
  yum:
    name:
      - automake
      - libtool
      - autoconf
      - autoconf-archive
      - libstdc++-devel
      - gcc
      - uriparser-devel
      - libgcrypt-devel
      - dbus-devel
      - glib2-devel
      # - compat-openssl10-devel -- There is a conflict
      - libcurl-devel
      - PyYAML
      - pandoc

- name: tools - Create Directory for tpm2-tools
  file:
    state: directory
    path: "/tmp/tpm2-tools"

- name: tools - Download Git Repo
  git:
    repo: https://github.com/tpm2-software/tpm2-tools.git
    version: "{{ tpm_tools_version }}"
    dest: "/tmp/tpm2-tools"

- name: tools - Execute tss bootstrap script
  shell: |
    ./bootstrap
  args:
    chdir: /tmp/tpm2-tools
    creates: /tmp/tpm2-tools/configure

- name: tools - Execute tss configure script
  shell: |
    ./configure
  args:
    chdir: /tmp/tpm2-tools
    creates: /tmp/tpm2-tools/Makefile
  environment:
    PKG_CONFIG_PATH: /usr/local/lib/pkgconfig

- name: tools - Compile Code using Make
  shell: |
    make
  args:
    chdir: /tmp/tpm2-tools
    #creates: /tmp/tpm2-tss/install-sh
  environment:
    GITIGNOREFILES:  # https://github.com/tpm2-software/tpm2-tss/issues/1636

- name: tools - Install tpm-tss
  shell: |
    make install
  args:
    chdir: /tmp/tpm2-tools
    creates: /usr/local/bin/tpm2_print
